/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type {
    ArsStatus,
    AssetDetailResponse,
    AssetScenariosResponse,
    Branch,
    DockerStats,
    EditProfileFileRequest,
    ErrorResponse,
    FileContentResponse,
    GetWorkshopParams,
    IPv4Response,
    ImageVersionResponse,
    ListScenariosResponse,
    LogType,
    PlayerIdentityId,
    PostServerBody,
    ProfileFileListResponse,
    PullLog,
    PutServerBody,
    ResultLogs,
    ResultSize,
    Server,
    SuccessResponse,
    UuidResponse,
    WorkshopResponse
} from './model';

export type getProfileFileResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getProfileFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getProfileFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getProfileFileResponseSuccess = getProfileFileResponse200 & {
    headers: Headers;
};
export type getProfileFileResponseError = (getProfileFileResponse400 | getProfileFileResponse404) & {
    headers: Headers;
};

export type getProfileFileResponse = getProfileFileResponseSuccess | getProfileFileResponseError;

export const getGetProfileFileUrl = (id: string, path: string) => {
    return `http://localhost:3000/api/v2/server/${id}/profile/${path}`;
};

export const getProfileFile = async (id: string, path: string, options?: RequestInit): Promise<getProfileFileResponse> => {
    const res = await fetch(getGetProfileFileUrl(id, path), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getProfileFileResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getProfileFileResponse;
};

export type putProfileFileResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type putProfileFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type putProfileFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type putProfileFileResponseSuccess = putProfileFileResponse200 & {
    headers: Headers;
};
export type putProfileFileResponseError = (putProfileFileResponse400 | putProfileFileResponse404) & {
    headers: Headers;
};

export type putProfileFileResponse = putProfileFileResponseSuccess | putProfileFileResponseError;

export const getPutProfileFileUrl = (id: string, path: string) => {
    return `http://localhost:3000/api/v2/server/${id}/profile/${path}`;
};

export const putProfileFile = async (
    id: string,
    path: string,
    editProfileFileRequest: EditProfileFileRequest,
    options?: RequestInit
): Promise<putProfileFileResponse> => {
    const res = await fetch(getPutProfileFileUrl(id, path), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(editProfileFileRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: putProfileFileResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as putProfileFileResponse;
};

export type getServersResponse200 = {
    data: Server[];
    status: 200;
};

export type getServersResponseSuccess = getServersResponse200 & {
    headers: Headers;
};
export type getServersResponse = getServersResponseSuccess;

export const getGetServersUrl = () => {
    return `http://localhost:3000/api/v2`;
};

export const getServers = async (options?: RequestInit): Promise<getServersResponse> => {
    const res = await fetch(getGetServersUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getServersResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getServersResponse;
};

export type getImageVersionResponse200 = {
    data: ImageVersionResponse;
    status: 200;
};

export type getImageVersionResponseSuccess = getImageVersionResponse200 & {
    headers: Headers;
};
export type getImageVersionResponse = getImageVersionResponseSuccess;

export const getGetImageVersionUrl = (branch: Branch) => {
    return `http://localhost:3000/api/v2/image-version/${branch}`;
};

export const getImageVersion = async (branch: Branch, options?: RequestInit): Promise<getImageVersionResponse> => {
    const res = await fetch(getGetImageVersionUrl(branch), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getImageVersionResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getImageVersionResponse;
};

export type getPublicIpResponse200 = {
    data: IPv4Response;
    status: 200;
};

export type getPublicIpResponseSuccess = getPublicIpResponse200 & {
    headers: Headers;
};
export type getPublicIpResponse = getPublicIpResponseSuccess;

export const getGetPublicIpUrl = () => {
    return `http://localhost:3000/api/v2/public-ip`;
};

export const getPublicIp = async (options?: RequestInit): Promise<getPublicIpResponse> => {
    const res = await fetch(getGetPublicIpUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPublicIpResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPublicIpResponse;
};

export type getPullImageResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type getPullImageResponseSuccess = getPullImageResponse200 & {
    headers: Headers;
};
export type getPullImageResponse = getPullImageResponseSuccess;

export const getGetPullImageUrl = (branch: Branch) => {
    return `http://localhost:3000/api/v2/pull/image/${branch}`;
};

export const getPullImage = async (branch: Branch, options?: RequestInit): Promise<getPullImageResponse> => {
    const res = await fetch(getGetPullImageUrl(branch), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPullImageResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPullImageResponse;
};

export type getPullLogsResponse200 = {
    data: PullLog[];
    status: 200;
};

export type getPullLogsResponseSuccess = getPullLogsResponse200 & {
    headers: Headers;
};
export type getPullLogsResponse = getPullLogsResponseSuccess;

export const getGetPullLogsUrl = () => {
    return `http://localhost:3000/api/v2/pull/logs`;
};

export const getPullLogs = async (options?: RequestInit): Promise<getPullLogsResponse> => {
    const res = await fetch(getGetPullLogsUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPullLogsResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPullLogsResponse;
};

export type getScenariosFromBranchResponse200 = {
    data: ListScenariosResponse;
    status: 200;
};

export type getScenariosFromBranchResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getScenariosFromBranchResponseSuccess = getScenariosFromBranchResponse200 & {
    headers: Headers;
};
export type getScenariosFromBranchResponseError = getScenariosFromBranchResponse500 & {
    headers: Headers;
};

export type getScenariosFromBranchResponse = getScenariosFromBranchResponseSuccess | getScenariosFromBranchResponseError;

export const getGetScenariosFromBranchUrl = (branch: Branch) => {
    return `http://localhost:3000/api/v2/scenarios/${branch}`;
};

export const getScenariosFromBranch = async (branch: Branch, options?: RequestInit): Promise<getScenariosFromBranchResponse> => {
    const res = await fetch(getGetScenariosFromBranchUrl(branch), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getScenariosFromBranchResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getScenariosFromBranchResponse;
};

export type updateScenariosFromBranchResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type updateScenariosFromBranchResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type updateScenariosFromBranchResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type updateScenariosFromBranchResponseSuccess = updateScenariosFromBranchResponse200 & {
    headers: Headers;
};
export type updateScenariosFromBranchResponseError = (updateScenariosFromBranchResponse404 | updateScenariosFromBranchResponse500) & {
    headers: Headers;
};

export type updateScenariosFromBranchResponse = updateScenariosFromBranchResponseSuccess | updateScenariosFromBranchResponseError;

export const getUpdateScenariosFromBranchUrl = (branch: Branch) => {
    return `http://localhost:3000/api/v2/scenarios/${branch}`;
};

export const updateScenariosFromBranch = async (branch: Branch, options?: RequestInit): Promise<updateScenariosFromBranchResponse> => {
    const res = await fetch(getUpdateScenariosFromBranchUrl(branch), {
        ...options,
        method: 'PUT'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: updateScenariosFromBranchResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as updateScenariosFromBranchResponse;
};

export type putServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type putServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type putServerResponseSuccess = putServerResponse200 & {
    headers: Headers;
};
export type putServerResponseError = putServerResponse400 & {
    headers: Headers;
};

export type putServerResponse = putServerResponseSuccess | putServerResponseError;

export const getPutServerUrl = () => {
    return `http://localhost:3000/api/v2/server`;
};

export const putServer = async (putServerBody: PutServerBody, options?: RequestInit): Promise<putServerResponse> => {
    const res = await fetch(getPutServerUrl(), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(putServerBody)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: putServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as putServerResponse;
};

export type postServerResponse200 = {
    data: UuidResponse;
    status: 200;
};

export type postServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type postServerResponseSuccess = postServerResponse200 & {
    headers: Headers;
};
export type postServerResponseError = postServerResponse400 & {
    headers: Headers;
};

export type postServerResponse = postServerResponseSuccess | postServerResponseError;

export const getPostServerUrl = () => {
    return `http://localhost:3000/api/v2/server`;
};

export const postServer = async (postServerBody: PostServerBody, options?: RequestInit): Promise<postServerResponse> => {
    const res = await fetch(getPostServerUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(postServerBody)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: postServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as postServerResponse;
};

export type getPlayerLogResponse200 = {
    data: PlayerIdentityId[];
    status: 200;
};

export type getPlayerLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getPlayerLogResponseSuccess = getPlayerLogResponse200 & {
    headers: Headers;
};
export type getPlayerLogResponseError = getPlayerLogResponse404 & {
    headers: Headers;
};

export type getPlayerLogResponse = getPlayerLogResponseSuccess | getPlayerLogResponseError;

export const getGetPlayerLogUrl = () => {
    return `http://localhost:3000/api/v2/server/known-players`;
};

export const getPlayerLog = async (options?: RequestInit): Promise<getPlayerLogResponse> => {
    const res = await fetch(getGetPlayerLogUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPlayerLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPlayerLogResponse;
};

export type getServerResponse200 = {
    data: Server;
    status: 200;
};

export type getServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getServerResponseSuccess = getServerResponse200 & {
    headers: Headers;
};
export type getServerResponseError = getServerResponse404 & {
    headers: Headers;
};

export type getServerResponse = getServerResponseSuccess | getServerResponseError;

export const getGetServerUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}`;
};

export const getServer = async (id: string, options?: RequestInit): Promise<getServerResponse> => {
    const res = await fetch(getGetServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getServerResponse;
};

export type deleteServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteServerResponseSuccess = deleteServerResponse200 & {
    headers: Headers;
};
export type deleteServerResponseError = deleteServerResponse404 & {
    headers: Headers;
};

export type deleteServerResponse = deleteServerResponseSuccess | deleteServerResponseError;

export const getDeleteServerUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}`;
};

export const deleteServer = async (id: string, options?: RequestInit): Promise<deleteServerResponse> => {
    const res = await fetch(getDeleteServerUrl(id), {
        ...options,
        method: 'DELETE'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as deleteServerResponse;
};

export type getCrashLogResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getCrashLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getCrashLogResponseSuccess = getCrashLogResponse200 & {
    headers: Headers;
};
export type getCrashLogResponseError = getCrashLogResponse404 & {
    headers: Headers;
};

export type getCrashLogResponse = getCrashLogResponseSuccess | getCrashLogResponseError;

export const getGetCrashLogUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/crash-reports-log`;
};

export const getCrashLog = async (id: string, options?: RequestInit): Promise<getCrashLogResponse> => {
    const res = await fetch(getGetCrashLogUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getCrashLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getCrashLogResponse;
};

export type isServerRunningResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type isServerRunningResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type isServerRunningResponseSuccess = isServerRunningResponse200 & {
    headers: Headers;
};
export type isServerRunningResponseError = isServerRunningResponse404 & {
    headers: Headers;
};

export type isServerRunningResponse = isServerRunningResponseSuccess | isServerRunningResponseError;

export const getIsServerRunningUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/is-running`;
};

export const isServerRunning = async (id: string, options?: RequestInit): Promise<isServerRunningResponse> => {
    const res = await fetch(getIsServerRunningUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: isServerRunningResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as isServerRunningResponse;
};

export type getLogsResponse200 = {
    data: ResultLogs;
    status: 200;
};

export type getLogsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogsResponseSuccess = getLogsResponse200 & {
    headers: Headers;
};
export type getLogsResponseError = getLogsResponse404 & {
    headers: Headers;
};

export type getLogsResponse = getLogsResponseSuccess | getLogsResponseError;

export const getGetLogsUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/logs`;
};

export const getLogs = async (id: string, options?: RequestInit): Promise<getLogsResponse> => {
    const res = await fetch(getGetLogsUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getLogsResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getLogsResponse;
};

export type deleteLogResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteLogResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type deleteLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteLogResponseSuccess = deleteLogResponse200 & {
    headers: Headers;
};
export type deleteLogResponseError = (deleteLogResponse400 | deleteLogResponse404) & {
    headers: Headers;
};

export type deleteLogResponse = deleteLogResponseSuccess | deleteLogResponseError;

export const getDeleteLogUrl = (id: string, log: string) => {
    return `http://localhost:3000/api/v2/server/${id}/logs/${log}`;
};

export const deleteLog = async (id: string, log: string, options?: RequestInit): Promise<deleteLogResponse> => {
    const res = await fetch(getDeleteLogUrl(id, log), {
        ...options,
        method: 'DELETE'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as deleteLogResponse;
};

export type getLogFileResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getLogFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getLogFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogFileResponseSuccess = getLogFileResponse200 & {
    headers: Headers;
};
export type getLogFileResponseError = (getLogFileResponse400 | getLogFileResponse404) & {
    headers: Headers;
};

export type getLogFileResponse = getLogFileResponseSuccess | getLogFileResponseError;

export const getGetLogFileUrl = (id: string, log: string, logType: LogType) => {
    return `http://localhost:3000/api/v2/server/${id}/logs/${log}/${logType}`;
};

export const getLogFile = async (id: string, log: string, logType: LogType, options?: RequestInit): Promise<getLogFileResponse> => {
    const res = await fetch(getGetLogFileUrl(id, log, logType), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getLogFileResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getLogFileResponse;
};

export type getProfileFilesResponse200 = {
    data: ProfileFileListResponse;
    status: 200;
};

export type getProfileFilesResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getProfileFilesResponseSuccess = getProfileFilesResponse200 & {
    headers: Headers;
};
export type getProfileFilesResponseError = getProfileFilesResponse404 & {
    headers: Headers;
};

export type getProfileFilesResponse = getProfileFilesResponseSuccess | getProfileFilesResponseError;

export const getGetProfileFilesUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/profile`;
};

export const getProfileFiles = async (id: string, options?: RequestInit): Promise<getProfileFilesResponse> => {
    const res = await fetch(getGetProfileFilesUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getProfileFilesResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getProfileFilesResponse;
};

export type getSizeMethodResponse200 = {
    data: ResultSize;
    status: 200;
};

export type getSizeMethodResponseSuccess = getSizeMethodResponse200 & {
    headers: Headers;
};
export type getSizeMethodResponse = getSizeMethodResponseSuccess;

export const getGetSizeMethodUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/size`;
};

export const getSizeMethod = async (id: string, options?: RequestInit): Promise<getSizeMethodResponse> => {
    const res = await fetch(getGetSizeMethodUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getSizeMethodResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getSizeMethodResponse;
};

export type startServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type startServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type startServerResponseSuccess = startServerResponse200 & {
    headers: Headers;
};
export type startServerResponseError = startServerResponse404 & {
    headers: Headers;
};

export type startServerResponse = startServerResponseSuccess | startServerResponseError;

export const getStartServerUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/start`;
};

export const startServer = async (id: string, options?: RequestInit): Promise<startServerResponse> => {
    const res = await fetch(getStartServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: startServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as startServerResponse;
};

export type getStatsResponse200 = {
    data: DockerStats;
    status: 200;
};

export type getStatsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
    headers: Headers;
};
export type getStatsResponseError = getStatsResponse404 & {
    headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/stats`;
};

export const getStats = async (id: string, options?: RequestInit): Promise<getStatsResponse> => {
    const res = await fetch(getGetStatsUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getStatsResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getStatsResponse;
};

export type stopServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type stopServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type stopServerResponseSuccess = stopServerResponse200 & {
    headers: Headers;
};
export type stopServerResponseError = stopServerResponse404 & {
    headers: Headers;
};

export type stopServerResponse = stopServerResponseSuccess | stopServerResponseError;

export const getStopServerUrl = (id: string) => {
    return `http://localhost:3000/api/v2/server/${id}/stop`;
};

export const stopServer = async (id: string, options?: RequestInit): Promise<stopServerResponse> => {
    const res = await fetch(getStopServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: stopServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as stopServerResponse;
};

export type getStatusResponse200 = {
    data: ArsStatus;
    status: 200;
};

export type getStatusResponseSuccess = getStatusResponse200 & {
    headers: Headers;
};
export type getStatusResponse = getStatusResponseSuccess;

export const getGetStatusUrl = () => {
    return `http://localhost:3000/api/v2/status`;
};

export const getStatus = async (options?: RequestInit): Promise<getStatusResponse> => {
    const res = await fetch(getGetStatusUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getStatusResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getStatusResponse;
};

export type getWorkshopResponse200 = {
    data: WorkshopResponse;
    status: 200;
};

export type getWorkshopResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getWorkshopResponseSuccess = getWorkshopResponse200 & {
    headers: Headers;
};
export type getWorkshopResponseError = getWorkshopResponse400 & {
    headers: Headers;
};

export type getWorkshopResponse = getWorkshopResponseSuccess | getWorkshopResponseError;

export const getGetWorkshopUrl = (params?: GetWorkshopParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `http://localhost:3000/api/v2/workshop?${stringifiedParams}`
        : `http://localhost:3000/api/v2/workshop`;
};

/**
 * Proxies requests to the upstream Arma Platform workshop API with optional
filtering by search term, tags, sort order, and page.
 * @summary Search the Arma Reforger Workshop
 */
export const getWorkshop = async (params?: GetWorkshopParams, options?: RequestInit): Promise<getWorkshopResponse> => {
    const res = await fetch(getGetWorkshopUrl(params), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getWorkshopResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getWorkshopResponse;
};

export type getWorkshopDetailResponse200 = {
    data: AssetDetailResponse;
    status: 200;
};

export type getWorkshopDetailResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getWorkshopDetailResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getWorkshopDetailResponseSuccess = getWorkshopDetailResponse200 & {
    headers: Headers;
};
export type getWorkshopDetailResponseError = (getWorkshopDetailResponse404 | getWorkshopDetailResponse500) & {
    headers: Headers;
};

export type getWorkshopDetailResponse = getWorkshopDetailResponseSuccess | getWorkshopDetailResponseError;

export const getGetWorkshopDetailUrl = (id: string) => {
    return `http://localhost:3000/api/v2/workshop/${id}`;
};

/**
 * The `id` path parameter is the asset ID (e.g. `5965550F24A0C152`).
The upstream slug format `{id}-{name}` is constructed automatically — just
pass the bare hex ID.
 * @summary Get full details for a single workshop asset, including its changelog
 */
export const getWorkshopDetail = async (id: string, options?: RequestInit): Promise<getWorkshopDetailResponse> => {
    const res = await fetch(getGetWorkshopDetailUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getWorkshopDetailResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getWorkshopDetailResponse;
};

export type getWorkshopScenariosResponse200 = {
    data: AssetScenariosResponse;
    status: 200;
};

export type getWorkshopScenariosResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getWorkshopScenariosResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getWorkshopScenariosResponseSuccess = getWorkshopScenariosResponse200 & {
    headers: Headers;
};
export type getWorkshopScenariosResponseError = (getWorkshopScenariosResponse404 | getWorkshopScenariosResponse500) & {
    headers: Headers;
};

export type getWorkshopScenariosResponse = getWorkshopScenariosResponseSuccess | getWorkshopScenariosResponseError;

export const getGetWorkshopScenariosUrl = (id: string) => {
    return `http://localhost:3000/api/v2/workshop/${id}/scenarios`;
};

/**
 * Maps to the upstream `/workshop/{id}/scenarios.json` endpoint.
Returns the scenarios bundled with the asset's current version, plus the
full resolved dependency list.
 * @summary List scenarios and dependencies for a workshop asset
 */
export const getWorkshopScenarios = async (id: string, options?: RequestInit): Promise<getWorkshopScenariosResponse> => {
    const res = await fetch(getGetWorkshopScenariosUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getWorkshopScenariosResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getWorkshopScenariosResponse;
};
