/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type {
    ArsStatus,
    AssetDetailResponse,
    AssetScenariosResponse,
    Branch,
    Claims,
    DockerStats,
    EditProfileFileRequest,
    ErrorResponse,
    FileContentResponse,
    GetGlobalLogsParams,
    GetWorkshopParams,
    IPv4Response,
    ImageVersionResponse,
    ListScenariosResponse,
    LogType,
    PaginatedResponseGlobalLog,
    PlayerIdentityId,
    PostServerBody,
    ProfileFileListResponse,
    PullLog,
    PutDefaultsBody,
    PutServerBody,
    ResultLogs,
    ResultSize,
    Server,
    ServerDefaults,
    SuccessResponse,
    UuidResponse,
    WorkshopResponse
} from './model';

import { customFetch } from '../utils/fetcher';
export type getProfileFileResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getProfileFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getProfileFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getProfileFileResponseSuccess = getProfileFileResponse200 & {
    headers: Headers;
};
export type getProfileFileResponseError = (getProfileFileResponse400 | getProfileFileResponse404) & {
    headers: Headers;
};

export type getProfileFileResponse = getProfileFileResponseSuccess | getProfileFileResponseError;

export const getGetProfileFileUrl = (id: string, path: string) => {
    return `/api/v2/server/${id}/profile/${path}`;
};

export const getProfileFile = async (id: string, path: string, options?: RequestInit): Promise<getProfileFileResponse> => {
    return customFetch<getProfileFileResponse>(getGetProfileFileUrl(id, path), {
        ...options,
        method: 'GET'
    });
};

export type putProfileFileResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type putProfileFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type putProfileFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type putProfileFileResponseSuccess = putProfileFileResponse200 & {
    headers: Headers;
};
export type putProfileFileResponseError = (putProfileFileResponse400 | putProfileFileResponse404) & {
    headers: Headers;
};

export type putProfileFileResponse = putProfileFileResponseSuccess | putProfileFileResponseError;

export const getPutProfileFileUrl = (id: string, path: string) => {
    return `/api/v2/server/${id}/profile/${path}`;
};

export const putProfileFile = async (
    id: string,
    path: string,
    editProfileFileRequest: EditProfileFileRequest,
    options?: RequestInit
): Promise<putProfileFileResponse> => {
    return customFetch<putProfileFileResponse>(getPutProfileFileUrl(id, path), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(editProfileFileRequest)
    });
};

export type getServersResponse200 = {
    data: Server[];
    status: 200;
};

export type getServersResponseSuccess = getServersResponse200 & {
    headers: Headers;
};
export type getServersResponse = getServersResponseSuccess;

export const getGetServersUrl = () => {
    return `/api/v2`;
};

export const getServers = async (options?: RequestInit): Promise<getServersResponse> => {
    return customFetch<getServersResponse>(getGetServersUrl(), {
        ...options,
        method: 'GET'
    });
};

export type callbackResponse303 = {
    data: void;
    status: 303;
};
export type callbackResponseError = callbackResponse303 & {
    headers: Headers;
};

export type callbackResponse = callbackResponseError;

export const getCallbackUrl = () => {
    return `/api/v2/auth/callback`;
};

export const callback = async (options?: RequestInit): Promise<callbackResponse> => {
    return customFetch<callbackResponse>(getCallbackUrl(), {
        ...options,
        method: 'GET'
    });
};

export type loginResponse303 = {
    data: void;
    status: 303;
};
export type loginResponseError = loginResponse303 & {
    headers: Headers;
};

export type loginResponse = loginResponseError;

export const getLoginUrl = () => {
    return `/api/v2/auth/login`;
};

export const login = async (options?: RequestInit): Promise<loginResponse> => {
    return customFetch<loginResponse>(getLoginUrl(), {
        ...options,
        method: 'GET'
    });
};

export type logoutResponse303 = {
    data: void;
    status: 303;
};
export type logoutResponseError = logoutResponse303 & {
    headers: Headers;
};

export type logoutResponse = logoutResponseError;

export const getLogoutUrl = () => {
    return `/api/v2/auth/logout`;
};

export const logout = async (options?: RequestInit): Promise<logoutResponse> => {
    return customFetch<logoutResponse>(getLogoutUrl(), {
        ...options,
        method: 'GET'
    });
};

export type userClaimsResponse200 = {
    data: Claims;
    status: 200;
};

export type userClaimsResponseSuccess = userClaimsResponse200 & {
    headers: Headers;
};
export type userClaimsResponse = userClaimsResponseSuccess;

export const getUserClaimsUrl = () => {
    return `/api/v2/auth/userclaims`;
};

export const userClaims = async (options?: RequestInit): Promise<userClaimsResponse> => {
    return customFetch<userClaimsResponse>(getUserClaimsUrl(), {
        ...options,
        method: 'GET'
    });
};

export type getDefaultsResponse200 = {
    data: ServerDefaults;
    status: 200;
};

export type getDefaultsResponseSuccess = getDefaultsResponse200 & {
    headers: Headers;
};
export type getDefaultsResponse = getDefaultsResponseSuccess;

export const getGetDefaultsUrl = () => {
    return `/api/v2/defaults`;
};

export const getDefaults = async (options?: RequestInit): Promise<getDefaultsResponse> => {
    return customFetch<getDefaultsResponse>(getGetDefaultsUrl(), {
        ...options,
        method: 'GET'
    });
};

export type putDefaultsResponse200 = {
    data: ServerDefaults;
    status: 200;
};

export type putDefaultsResponseSuccess = putDefaultsResponse200 & {
    headers: Headers;
};
export type putDefaultsResponse = putDefaultsResponseSuccess;

export const getPutDefaultsUrl = () => {
    return `/api/v2/defaults`;
};

export const putDefaults = async (putDefaultsBody: PutDefaultsBody, options?: RequestInit): Promise<putDefaultsResponse> => {
    return customFetch<putDefaultsResponse>(getPutDefaultsUrl(), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(putDefaultsBody)
    });
};

export type getImageVersionResponse200 = {
    data: ImageVersionResponse;
    status: 200;
};

export type getImageVersionResponseSuccess = getImageVersionResponse200 & {
    headers: Headers;
};
export type getImageVersionResponse = getImageVersionResponseSuccess;

export const getGetImageVersionUrl = (branch: Branch) => {
    return `/api/v2/image-version/${branch}`;
};

export const getImageVersion = async (branch: Branch, options?: RequestInit): Promise<getImageVersionResponse> => {
    return customFetch<getImageVersionResponse>(getGetImageVersionUrl(branch), {
        ...options,
        method: 'GET'
    });
};

export type getGlobalLogsResponse200 = {
    data: PaginatedResponseGlobalLog;
    status: 200;
};

export type getGlobalLogsResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getGlobalLogsResponseSuccess = getGlobalLogsResponse200 & {
    headers: Headers;
};
export type getGlobalLogsResponseError = getGlobalLogsResponse500 & {
    headers: Headers;
};

export type getGlobalLogsResponse = getGlobalLogsResponseSuccess | getGlobalLogsResponseError;

export const getGetGlobalLogsUrl = (params?: GetGlobalLogsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/api/v2/logs?${stringifiedParams}` : `/api/v2/logs`;
};

export const getGlobalLogs = async (params?: GetGlobalLogsParams, options?: RequestInit): Promise<getGlobalLogsResponse> => {
    return customFetch<getGlobalLogsResponse>(getGetGlobalLogsUrl(params), {
        ...options,
        method: 'GET'
    });
};

export type getPublicIpResponse200 = {
    data: IPv4Response;
    status: 200;
};

export type getPublicIpResponseSuccess = getPublicIpResponse200 & {
    headers: Headers;
};
export type getPublicIpResponse = getPublicIpResponseSuccess;

export const getGetPublicIpUrl = () => {
    return `/api/v2/public-ip`;
};

export const getPublicIp = async (options?: RequestInit): Promise<getPublicIpResponse> => {
    return customFetch<getPublicIpResponse>(getGetPublicIpUrl(), {
        ...options,
        method: 'GET'
    });
};

export type getPullImageResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type getPullImageResponseSuccess = getPullImageResponse200 & {
    headers: Headers;
};
export type getPullImageResponse = getPullImageResponseSuccess;

export const getGetPullImageUrl = (branch: Branch) => {
    return `/api/v2/pull/image/${branch}`;
};

export const getPullImage = async (branch: Branch, options?: RequestInit): Promise<getPullImageResponse> => {
    return customFetch<getPullImageResponse>(getGetPullImageUrl(branch), {
        ...options,
        method: 'GET'
    });
};

export type getPullLogsResponse200 = {
    data: PullLog[];
    status: 200;
};

export type getPullLogsResponseSuccess = getPullLogsResponse200 & {
    headers: Headers;
};
export type getPullLogsResponse = getPullLogsResponseSuccess;

export const getGetPullLogsUrl = () => {
    return `/api/v2/pull/logs`;
};

export const getPullLogs = async (options?: RequestInit): Promise<getPullLogsResponse> => {
    return customFetch<getPullLogsResponse>(getGetPullLogsUrl(), {
        ...options,
        method: 'GET'
    });
};

export type getScenariosFromBranchResponse200 = {
    data: ListScenariosResponse;
    status: 200;
};

export type getScenariosFromBranchResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getScenariosFromBranchResponseSuccess = getScenariosFromBranchResponse200 & {
    headers: Headers;
};
export type getScenariosFromBranchResponseError = getScenariosFromBranchResponse500 & {
    headers: Headers;
};

export type getScenariosFromBranchResponse = getScenariosFromBranchResponseSuccess | getScenariosFromBranchResponseError;

export const getGetScenariosFromBranchUrl = (branch: Branch) => {
    return `/api/v2/scenarios/${branch}`;
};

export const getScenariosFromBranch = async (branch: Branch, options?: RequestInit): Promise<getScenariosFromBranchResponse> => {
    return customFetch<getScenariosFromBranchResponse>(getGetScenariosFromBranchUrl(branch), {
        ...options,
        method: 'GET'
    });
};

export type updateScenariosFromBranchResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type updateScenariosFromBranchResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type updateScenariosFromBranchResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type updateScenariosFromBranchResponseSuccess = updateScenariosFromBranchResponse200 & {
    headers: Headers;
};
export type updateScenariosFromBranchResponseError = (updateScenariosFromBranchResponse404 | updateScenariosFromBranchResponse500) & {
    headers: Headers;
};

export type updateScenariosFromBranchResponse = updateScenariosFromBranchResponseSuccess | updateScenariosFromBranchResponseError;

export const getUpdateScenariosFromBranchUrl = (branch: Branch) => {
    return `/api/v2/scenarios/${branch}`;
};

export const updateScenariosFromBranch = async (branch: Branch, options?: RequestInit): Promise<updateScenariosFromBranchResponse> => {
    return customFetch<updateScenariosFromBranchResponse>(getUpdateScenariosFromBranchUrl(branch), {
        ...options,
        method: 'PUT'
    });
};

export type putServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type putServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type putServerResponseSuccess = putServerResponse200 & {
    headers: Headers;
};
export type putServerResponseError = putServerResponse400 & {
    headers: Headers;
};

export type putServerResponse = putServerResponseSuccess | putServerResponseError;

export const getPutServerUrl = () => {
    return `/api/v2/server`;
};

export const putServer = async (putServerBody: PutServerBody, options?: RequestInit): Promise<putServerResponse> => {
    return customFetch<putServerResponse>(getPutServerUrl(), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(putServerBody)
    });
};

export type postServerResponse200 = {
    data: UuidResponse;
    status: 200;
};

export type postServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type postServerResponseSuccess = postServerResponse200 & {
    headers: Headers;
};
export type postServerResponseError = postServerResponse400 & {
    headers: Headers;
};

export type postServerResponse = postServerResponseSuccess | postServerResponseError;

export const getPostServerUrl = () => {
    return `/api/v2/server`;
};

export const postServer = async (postServerBody: PostServerBody, options?: RequestInit): Promise<postServerResponse> => {
    return customFetch<postServerResponse>(getPostServerUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(postServerBody)
    });
};

export type getPlayerLogResponse200 = {
    data: PlayerIdentityId[];
    status: 200;
};

export type getPlayerLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getPlayerLogResponseSuccess = getPlayerLogResponse200 & {
    headers: Headers;
};
export type getPlayerLogResponseError = getPlayerLogResponse404 & {
    headers: Headers;
};

export type getPlayerLogResponse = getPlayerLogResponseSuccess | getPlayerLogResponseError;

export const getGetPlayerLogUrl = () => {
    return `/api/v2/server/known-players`;
};

export const getPlayerLog = async (options?: RequestInit): Promise<getPlayerLogResponse> => {
    return customFetch<getPlayerLogResponse>(getGetPlayerLogUrl(), {
        ...options,
        method: 'GET'
    });
};

export type getServerResponse200 = {
    data: Server;
    status: 200;
};

export type getServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getServerResponseSuccess = getServerResponse200 & {
    headers: Headers;
};
export type getServerResponseError = getServerResponse404 & {
    headers: Headers;
};

export type getServerResponse = getServerResponseSuccess | getServerResponseError;

export const getGetServerUrl = (id: string) => {
    return `/api/v2/server/${id}`;
};

export const getServer = async (id: string, options?: RequestInit): Promise<getServerResponse> => {
    return customFetch<getServerResponse>(getGetServerUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type deleteServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteServerResponseSuccess = deleteServerResponse200 & {
    headers: Headers;
};
export type deleteServerResponseError = deleteServerResponse404 & {
    headers: Headers;
};

export type deleteServerResponse = deleteServerResponseSuccess | deleteServerResponseError;

export const getDeleteServerUrl = (id: string) => {
    return `/api/v2/server/${id}`;
};

export const deleteServer = async (id: string, options?: RequestInit): Promise<deleteServerResponse> => {
    return customFetch<deleteServerResponse>(getDeleteServerUrl(id), {
        ...options,
        method: 'DELETE'
    });
};

export type getCrashLogResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getCrashLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getCrashLogResponseSuccess = getCrashLogResponse200 & {
    headers: Headers;
};
export type getCrashLogResponseError = getCrashLogResponse404 & {
    headers: Headers;
};

export type getCrashLogResponse = getCrashLogResponseSuccess | getCrashLogResponseError;

export const getGetCrashLogUrl = (id: string) => {
    return `/api/v2/server/${id}/crash-reports-log`;
};

export const getCrashLog = async (id: string, options?: RequestInit): Promise<getCrashLogResponse> => {
    return customFetch<getCrashLogResponse>(getGetCrashLogUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type isServerRunningResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type isServerRunningResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type isServerRunningResponseSuccess = isServerRunningResponse200 & {
    headers: Headers;
};
export type isServerRunningResponseError = isServerRunningResponse404 & {
    headers: Headers;
};

export type isServerRunningResponse = isServerRunningResponseSuccess | isServerRunningResponseError;

export const getIsServerRunningUrl = (id: string) => {
    return `/api/v2/server/${id}/is-running`;
};

export const isServerRunning = async (id: string, options?: RequestInit): Promise<isServerRunningResponse> => {
    return customFetch<isServerRunningResponse>(getIsServerRunningUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type getLogsResponse200 = {
    data: ResultLogs;
    status: 200;
};

export type getLogsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogsResponseSuccess = getLogsResponse200 & {
    headers: Headers;
};
export type getLogsResponseError = getLogsResponse404 & {
    headers: Headers;
};

export type getLogsResponse = getLogsResponseSuccess | getLogsResponseError;

export const getGetLogsUrl = (id: string) => {
    return `/api/v2/server/${id}/logs`;
};

export const getLogs = async (id: string, options?: RequestInit): Promise<getLogsResponse> => {
    return customFetch<getLogsResponse>(getGetLogsUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type deleteLogResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteLogResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type deleteLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteLogResponseSuccess = deleteLogResponse200 & {
    headers: Headers;
};
export type deleteLogResponseError = (deleteLogResponse400 | deleteLogResponse404) & {
    headers: Headers;
};

export type deleteLogResponse = deleteLogResponseSuccess | deleteLogResponseError;

export const getDeleteLogUrl = (id: string, log: string) => {
    return `/api/v2/server/${id}/logs/${log}`;
};

export const deleteLog = async (id: string, log: string, options?: RequestInit): Promise<deleteLogResponse> => {
    return customFetch<deleteLogResponse>(getDeleteLogUrl(id, log), {
        ...options,
        method: 'DELETE'
    });
};

export type getLogFileResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getLogFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getLogFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogFileResponseSuccess = getLogFileResponse200 & {
    headers: Headers;
};
export type getLogFileResponseError = (getLogFileResponse400 | getLogFileResponse404) & {
    headers: Headers;
};

export type getLogFileResponse = getLogFileResponseSuccess | getLogFileResponseError;

export const getGetLogFileUrl = (id: string, log: string, logType: LogType) => {
    return `/api/v2/server/${id}/logs/${log}/${logType}`;
};

export const getLogFile = async (id: string, log: string, logType: LogType, options?: RequestInit): Promise<getLogFileResponse> => {
    return customFetch<getLogFileResponse>(getGetLogFileUrl(id, log, logType), {
        ...options,
        method: 'GET'
    });
};

export type getProfileFilesResponse200 = {
    data: ProfileFileListResponse;
    status: 200;
};

export type getProfileFilesResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getProfileFilesResponseSuccess = getProfileFilesResponse200 & {
    headers: Headers;
};
export type getProfileFilesResponseError = getProfileFilesResponse404 & {
    headers: Headers;
};

export type getProfileFilesResponse = getProfileFilesResponseSuccess | getProfileFilesResponseError;

export const getGetProfileFilesUrl = (id: string) => {
    return `/api/v2/server/${id}/profile`;
};

export const getProfileFiles = async (id: string, options?: RequestInit): Promise<getProfileFilesResponse> => {
    return customFetch<getProfileFilesResponse>(getGetProfileFilesUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type getSizeMethodResponse200 = {
    data: ResultSize;
    status: 200;
};

export type getSizeMethodResponseSuccess = getSizeMethodResponse200 & {
    headers: Headers;
};
export type getSizeMethodResponse = getSizeMethodResponseSuccess;

export const getGetSizeMethodUrl = (id: string) => {
    return `/api/v2/server/${id}/size`;
};

export const getSizeMethod = async (id: string, options?: RequestInit): Promise<getSizeMethodResponse> => {
    return customFetch<getSizeMethodResponse>(getGetSizeMethodUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type startServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type startServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type startServerResponseSuccess = startServerResponse200 & {
    headers: Headers;
};
export type startServerResponseError = startServerResponse404 & {
    headers: Headers;
};

export type startServerResponse = startServerResponseSuccess | startServerResponseError;

export const getStartServerUrl = (id: string) => {
    return `/api/v2/server/${id}/start`;
};

export const startServer = async (id: string, options?: RequestInit): Promise<startServerResponse> => {
    return customFetch<startServerResponse>(getStartServerUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type getStatsResponse200 = {
    data: DockerStats;
    status: 200;
};

export type getStatsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
    headers: Headers;
};
export type getStatsResponseError = getStatsResponse404 & {
    headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (id: string) => {
    return `/api/v2/server/${id}/stats`;
};

export const getStats = async (id: string, options?: RequestInit): Promise<getStatsResponse> => {
    return customFetch<getStatsResponse>(getGetStatsUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type stopServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type stopServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type stopServerResponseSuccess = stopServerResponse200 & {
    headers: Headers;
};
export type stopServerResponseError = stopServerResponse404 & {
    headers: Headers;
};

export type stopServerResponse = stopServerResponseSuccess | stopServerResponseError;

export const getStopServerUrl = (id: string) => {
    return `/api/v2/server/${id}/stop`;
};

export const stopServer = async (id: string, options?: RequestInit): Promise<stopServerResponse> => {
    return customFetch<stopServerResponse>(getStopServerUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type getStatusResponse200 = {
    data: ArsStatus;
    status: 200;
};

export type getStatusResponseSuccess = getStatusResponse200 & {
    headers: Headers;
};
export type getStatusResponse = getStatusResponseSuccess;

export const getGetStatusUrl = () => {
    return `/api/v2/status`;
};

export const getStatus = async (options?: RequestInit): Promise<getStatusResponse> => {
    return customFetch<getStatusResponse>(getGetStatusUrl(), {
        ...options,
        method: 'GET'
    });
};

export type getWorkshopResponse200 = {
    data: WorkshopResponse;
    status: 200;
};

export type getWorkshopResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getWorkshopResponseSuccess = getWorkshopResponse200 & {
    headers: Headers;
};
export type getWorkshopResponseError = getWorkshopResponse400 & {
    headers: Headers;
};

export type getWorkshopResponse = getWorkshopResponseSuccess | getWorkshopResponseError;

export const getGetWorkshopUrl = (params?: GetWorkshopParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/api/v2/workshop?${stringifiedParams}` : `/api/v2/workshop`;
};

/**
 * Proxies requests to the upstream Arma Platform workshop API with optional
filtering by search term, tags, sort order, and page.
 * @summary Search the Arma Reforger Workshop
 */
export const getWorkshop = async (params?: GetWorkshopParams, options?: RequestInit): Promise<getWorkshopResponse> => {
    return customFetch<getWorkshopResponse>(getGetWorkshopUrl(params), {
        ...options,
        method: 'GET'
    });
};

export type getWorkshopDetailResponse200 = {
    data: AssetDetailResponse;
    status: 200;
};

export type getWorkshopDetailResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getWorkshopDetailResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getWorkshopDetailResponseSuccess = getWorkshopDetailResponse200 & {
    headers: Headers;
};
export type getWorkshopDetailResponseError = (getWorkshopDetailResponse404 | getWorkshopDetailResponse500) & {
    headers: Headers;
};

export type getWorkshopDetailResponse = getWorkshopDetailResponseSuccess | getWorkshopDetailResponseError;

export const getGetWorkshopDetailUrl = (id: string) => {
    return `/api/v2/workshop/${id}`;
};

/**
 * The `id` path parameter is the asset ID (e.g. `5965550F24A0C152`).
The upstream slug format `{id}-{name}` is constructed automatically — just
pass the bare hex ID.
 * @summary Get full details for a single workshop asset, including its changelog
 */
export const getWorkshopDetail = async (id: string, options?: RequestInit): Promise<getWorkshopDetailResponse> => {
    return customFetch<getWorkshopDetailResponse>(getGetWorkshopDetailUrl(id), {
        ...options,
        method: 'GET'
    });
};

export type getWorkshopScenariosResponse200 = {
    data: AssetScenariosResponse;
    status: 200;
};

export type getWorkshopScenariosResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getWorkshopScenariosResponse500 = {
    data: ErrorResponse;
    status: 500;
};

export type getWorkshopScenariosResponseSuccess = getWorkshopScenariosResponse200 & {
    headers: Headers;
};
export type getWorkshopScenariosResponseError = (getWorkshopScenariosResponse404 | getWorkshopScenariosResponse500) & {
    headers: Headers;
};

export type getWorkshopScenariosResponse = getWorkshopScenariosResponseSuccess | getWorkshopScenariosResponseError;

export const getGetWorkshopScenariosUrl = (id: string) => {
    return `/api/v2/workshop/${id}/scenarios`;
};

/**
 * Maps to the upstream `/workshop/{id}/scenarios.json` endpoint.
Returns the scenarios bundled with the asset's current version, plus the
full resolved dependency list.
 * @summary List scenarios and dependencies for a workshop asset
 */
export const getWorkshopScenarios = async (id: string, options?: RequestInit): Promise<getWorkshopScenariosResponse> => {
    return customFetch<getWorkshopScenariosResponse>(getGetWorkshopScenariosUrl(id), {
        ...options,
        method: 'GET'
    });
};
