/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type {
    ArsStatus,
    Branch,
    DockerStats,
    ErrorResponse,
    FileContentResponse,
    IPv4Response,
    LogType,
    PlayerIdentityId,
    PostServerBody,
    PutServerBody,
    ResultLogs,
    ResultSize,
    Server,
    SuccessResponse,
    UuidResponse
} from './model';

export type getServersResponse200 = {
    data: Server[];
    status: 200;
};

export type getServersResponseSuccess = getServersResponse200 & {
    headers: Headers;
};
export type getServersResponse = getServersResponseSuccess;

export const getGetServersUrl = () => {
    return `http://localhost:3000/api/v1`;
};

export const getServers = async (options?: RequestInit): Promise<getServersResponse> => {
    const res = await fetch(getGetServersUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getServersResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getServersResponse;
};

export type getPublicIpResponse200 = {
    data: IPv4Response;
    status: 200;
};

export type getPublicIpResponseSuccess = getPublicIpResponse200 & {
    headers: Headers;
};
export type getPublicIpResponse = getPublicIpResponseSuccess;

export const getGetPublicIpUrl = () => {
    return `http://localhost:3000/api/v1/public-ip`;
};

export const getPublicIp = async (options?: RequestInit): Promise<getPublicIpResponse> => {
    const res = await fetch(getGetPublicIpUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPublicIpResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPublicIpResponse;
};

export type getPullImageResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type getPullImageResponseSuccess = getPullImageResponse200 & {
    headers: Headers;
};
export type getPullImageResponse = getPullImageResponseSuccess;

export const getGetPullImageUrl = (branch: Branch) => {
    return `http://localhost:3000/api/v1/pull-image/${branch}`;
};

export const getPullImage = async (branch: Branch, options?: RequestInit): Promise<getPullImageResponse> => {
    const res = await fetch(getGetPullImageUrl(branch), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPullImageResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPullImageResponse;
};

export type putServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type putServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type putServerResponseSuccess = putServerResponse200 & {
    headers: Headers;
};
export type putServerResponseError = putServerResponse400 & {
    headers: Headers;
};

export type putServerResponse = putServerResponseSuccess | putServerResponseError;

export const getPutServerUrl = () => {
    return `http://localhost:3000/api/v1/server`;
};

export const putServer = async (putServerBody: PutServerBody, options?: RequestInit): Promise<putServerResponse> => {
    const res = await fetch(getPutServerUrl(), {
        ...options,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(putServerBody)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: putServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as putServerResponse;
};

export type postServerResponse200 = {
    data: UuidResponse;
    status: 200;
};

export type postServerResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type postServerResponseSuccess = postServerResponse200 & {
    headers: Headers;
};
export type postServerResponseError = postServerResponse400 & {
    headers: Headers;
};

export type postServerResponse = postServerResponseSuccess | postServerResponseError;

export const getPostServerUrl = () => {
    return `http://localhost:3000/api/v1/server`;
};

export const postServer = async (postServerBody: PostServerBody, options?: RequestInit): Promise<postServerResponse> => {
    const res = await fetch(getPostServerUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(postServerBody)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: postServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as postServerResponse;
};

export type getPlayerLogResponse200 = {
    data: PlayerIdentityId[];
    status: 200;
};

export type getPlayerLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getPlayerLogResponseSuccess = getPlayerLogResponse200 & {
    headers: Headers;
};
export type getPlayerLogResponseError = getPlayerLogResponse404 & {
    headers: Headers;
};

export type getPlayerLogResponse = getPlayerLogResponseSuccess | getPlayerLogResponseError;

export const getGetPlayerLogUrl = () => {
    return `http://localhost:3000/api/v1/server/known-players`;
};

export const getPlayerLog = async (options?: RequestInit): Promise<getPlayerLogResponse> => {
    const res = await fetch(getGetPlayerLogUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getPlayerLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getPlayerLogResponse;
};

export type getServerResponse200 = {
    data: Server;
    status: 200;
};

export type getServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getServerResponseSuccess = getServerResponse200 & {
    headers: Headers;
};
export type getServerResponseError = getServerResponse404 & {
    headers: Headers;
};

export type getServerResponse = getServerResponseSuccess | getServerResponseError;

export const getGetServerUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}`;
};

export const getServer = async (id: string, options?: RequestInit): Promise<getServerResponse> => {
    const res = await fetch(getGetServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getServerResponse;
};

export type deleteServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteServerResponseSuccess = deleteServerResponse200 & {
    headers: Headers;
};
export type deleteServerResponseError = deleteServerResponse404 & {
    headers: Headers;
};

export type deleteServerResponse = deleteServerResponseSuccess | deleteServerResponseError;

export const getDeleteServerUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}`;
};

export const deleteServer = async (id: string, options?: RequestInit): Promise<deleteServerResponse> => {
    const res = await fetch(getDeleteServerUrl(id), {
        ...options,
        method: 'DELETE'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as deleteServerResponse;
};

export type getCrashLogResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getCrashLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getCrashLogResponseSuccess = getCrashLogResponse200 & {
    headers: Headers;
};
export type getCrashLogResponseError = getCrashLogResponse404 & {
    headers: Headers;
};

export type getCrashLogResponse = getCrashLogResponseSuccess | getCrashLogResponseError;

export const getGetCrashLogUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/crash-reports-log`;
};

export const getCrashLog = async (id: string, options?: RequestInit): Promise<getCrashLogResponse> => {
    const res = await fetch(getGetCrashLogUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getCrashLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getCrashLogResponse;
};

export type isServerRunningResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type isServerRunningResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type isServerRunningResponseSuccess = isServerRunningResponse200 & {
    headers: Headers;
};
export type isServerRunningResponseError = isServerRunningResponse404 & {
    headers: Headers;
};

export type isServerRunningResponse = isServerRunningResponseSuccess | isServerRunningResponseError;

export const getIsServerRunningUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/is-running`;
};

export const isServerRunning = async (id: string, options?: RequestInit): Promise<isServerRunningResponse> => {
    const res = await fetch(getIsServerRunningUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: isServerRunningResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as isServerRunningResponse;
};

export type getLogsResponse200 = {
    data: ResultLogs;
    status: 200;
};

export type getLogsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogsResponseSuccess = getLogsResponse200 & {
    headers: Headers;
};
export type getLogsResponseError = getLogsResponse404 & {
    headers: Headers;
};

export type getLogsResponse = getLogsResponseSuccess | getLogsResponseError;

export const getGetLogsUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/logs`;
};

export const getLogs = async (id: string, options?: RequestInit): Promise<getLogsResponse> => {
    const res = await fetch(getGetLogsUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getLogsResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getLogsResponse;
};

export type deleteLogResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type deleteLogResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type deleteLogResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type deleteLogResponseSuccess = deleteLogResponse200 & {
    headers: Headers;
};
export type deleteLogResponseError = (deleteLogResponse400 | deleteLogResponse404) & {
    headers: Headers;
};

export type deleteLogResponse = deleteLogResponseSuccess | deleteLogResponseError;

export const getDeleteLogUrl = (id: string, log: string) => {
    return `http://localhost:3000/api/v1/server/${id}/logs/${log}`;
};

export const deleteLog = async (id: string, log: string, options?: RequestInit): Promise<deleteLogResponse> => {
    const res = await fetch(getDeleteLogUrl(id, log), {
        ...options,
        method: 'DELETE'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteLogResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as deleteLogResponse;
};

export type getLogFileResponse200 = {
    data: FileContentResponse;
    status: 200;
};

export type getLogFileResponse400 = {
    data: ErrorResponse;
    status: 400;
};

export type getLogFileResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getLogFileResponseSuccess = getLogFileResponse200 & {
    headers: Headers;
};
export type getLogFileResponseError = (getLogFileResponse400 | getLogFileResponse404) & {
    headers: Headers;
};

export type getLogFileResponse = getLogFileResponseSuccess | getLogFileResponseError;

export const getGetLogFileUrl = (id: string, log: string, logType: LogType) => {
    return `http://localhost:3000/api/v1/server/${id}/logs/${log}/${logType}`;
};

export const getLogFile = async (id: string, log: string, logType: LogType, options?: RequestInit): Promise<getLogFileResponse> => {
    const res = await fetch(getGetLogFileUrl(id, log, logType), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getLogFileResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getLogFileResponse;
};

export type getSizeMethodResponse200 = {
    data: ResultSize;
    status: 200;
};

export type getSizeMethodResponseSuccess = getSizeMethodResponse200 & {
    headers: Headers;
};
export type getSizeMethodResponse = getSizeMethodResponseSuccess;

export const getGetSizeMethodUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/size`;
};

export const getSizeMethod = async (id: string, options?: RequestInit): Promise<getSizeMethodResponse> => {
    const res = await fetch(getGetSizeMethodUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getSizeMethodResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getSizeMethodResponse;
};

export type startServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type startServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type startServerResponseSuccess = startServerResponse200 & {
    headers: Headers;
};
export type startServerResponseError = startServerResponse404 & {
    headers: Headers;
};

export type startServerResponse = startServerResponseSuccess | startServerResponseError;

export const getStartServerUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/start`;
};

export const startServer = async (id: string, options?: RequestInit): Promise<startServerResponse> => {
    const res = await fetch(getStartServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: startServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as startServerResponse;
};

export type getStatsResponse200 = {
    data: DockerStats;
    status: 200;
};

export type getStatsResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
    headers: Headers;
};
export type getStatsResponseError = getStatsResponse404 & {
    headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/stats`;
};

export const getStats = async (id: string, options?: RequestInit): Promise<getStatsResponse> => {
    const res = await fetch(getGetStatsUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getStatsResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getStatsResponse;
};

export type stopServerResponse200 = {
    data: SuccessResponse;
    status: 200;
};

export type stopServerResponse404 = {
    data: ErrorResponse;
    status: 404;
};

export type stopServerResponseSuccess = stopServerResponse200 & {
    headers: Headers;
};
export type stopServerResponseError = stopServerResponse404 & {
    headers: Headers;
};

export type stopServerResponse = stopServerResponseSuccess | stopServerResponseError;

export const getStopServerUrl = (id: string) => {
    return `http://localhost:3000/api/v1/server/${id}/stop`;
};

export const stopServer = async (id: string, options?: RequestInit): Promise<stopServerResponse> => {
    const res = await fetch(getStopServerUrl(id), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: stopServerResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as stopServerResponse;
};

export type getStatusResponse200 = {
    data: ArsStatus;
    status: 200;
};

export type getStatusResponseSuccess = getStatusResponse200 & {
    headers: Headers;
};
export type getStatusResponse = getStatusResponseSuccess;

export const getGetStatusUrl = () => {
    return `http://localhost:3000/api/v1/status`;
};

export const getStatus = async (options?: RequestInit): Promise<getStatusResponse> => {
    const res = await fetch(getGetStatusUrl(), {
        ...options,
        method: 'GET'
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getStatusResponse['data'] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getStatusResponse;
};
