/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface A2s {
    address: string;
    /** @minimum 0 */
    port: number;
}
