/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export type ArsStatus = (typeof ArsStatus)[keyof typeof ArsStatus];

export const ArsStatus = {
    Unknown: 'Unknown',
    Available: 'Available',
    Recreating: 'Recreating',
    RecreatingFailure: 'RecreatingFailure',
    Unavailable: 'Unavailable'
} as const;
