/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { Dependency } from './dependency';
import type { Scenario } from './scenario';

export interface AssetVersionDetail {
    /**
     * Changelog text for the current version
     * @nullable
     */
    changelog?: string | null;
    dependencies: Dependency[];
    scenarios: Scenario[];
}
