/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { AssetDetail } from './assetDetail';
import type { AssetVersionDetail } from './assetVersionDetail';

/**
 * Response for the asset detail endpoint
 */
export interface AssetDetailResponse {
    asset: AssetDetail;
    /**
     * All-time download count
     * @minimum 0
     */
    download_total: number;
    /** Changelog and dependency info for the current version */
    version_detail: AssetVersionDetail;
}
