/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export interface AssetVersion {
    approved: boolean;
    assetId: string;
    createdAt: string;
    /** @minimum 0 */
    dependenciesCount: number;
    gameVersion: string;
    milestone: boolean;
    published: boolean;
    /** @minimum 0 */
    scenariosCount: number;
    /** @minimum 0 */
    totalFileSize: number;
    updatedAt: string;
    version: string;
}
