/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { AssetTag } from './assetTag';
import type { AssetVersion } from './assetVersion';
import type { Author } from './author';
import type { Preview } from './preview';
import type { Ratings } from './ratings';
import type { Screenshot } from './screenshot';

/**
 * Full asset detail including all versions, ratings, changelog, and download count
 */
export interface AssetDetail {
    author: Author;
    averageRating: number;
    blocked: boolean;
    createdAt: string;
    currentVersionNumber: string;
    /** @minimum 0 */
    currentVersionSize: number;
    /** @nullable */
    description?: string | null;
    gameVersion: string;
    id: string;
    /** @nullable */
    license?: string | null;
    name: string;
    obsolete: boolean;
    previews: Preview[];
    private: boolean;
    /** @minimum 0 */
    ratingCount: number;
    ratings: Ratings;
    screenshots: Screenshot[];
    /** @minimum 0 */
    subscriberCount: number;
    summary: string;
    tags: AssetTag[];
    type: string;
    unlisted: boolean;
    updatedAt: string;
    versions: AssetVersion[];
}
