/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { Asset } from './asset';

export interface AssetsPage {
    /** @minimum 0 */
    count: number;
    rows: Asset[];
}
