/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { AssetTag } from './assetTag';
import type { Author } from './author';
import type { Preview } from './preview';

export interface Asset {
    author: Author;
    averageRating: number;
    blocked: boolean;
    createdAt: string;
    currentVersionNumber: string;
    /** @minimum 0 */
    currentVersionSize: number;
    id: string;
    name: string;
    previews: Preview[];
    private: boolean;
    /** @minimum 0 */
    ratingCount: number;
    /** @minimum 0 */
    subscriberCount: number;
    summary: string;
    tags: AssetTag[];
    type: string;
    unlisted: boolean;
    updatedAt: string;
}
