/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { Dependency } from './dependency';
import type { Scenario } from './scenario';

/**
 * Response for the scenarios endpoint
 */
export interface AssetScenariosResponse {
    asset_id: string;
    dependencies: Dependency[];
    scenarios: Scenario[];
}
