/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export type Branch = (typeof Branch)[keyof typeof Branch];

export const Branch = {
    stable: 'stable',
    experimental: 'experimental'
} as const;
