/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export type Branch = (typeof Branch)[keyof typeof Branch];

export const Branch = {
    stable: 'stable',
    experimental: 'experimental'
} as const;
