/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { RealmAccess } from './realmAccess';

export interface Claims {
    /** @minimum 0 */
    exp: number;
    /** @nullable */
    picture?: string | null;
    /** @nullable */
    preferred_username?: string | null;
    realm_access?: null | RealmAccess;
    sub: string;
}
