/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { DependencyAssetStub } from './dependencyAssetStub';

export interface Dependency {
    asset?: DependencyAssetStub;
    blocked?: boolean;
    dependencies?: Dependency[];
    private?: boolean;
    published?: boolean;
    /** @minimum 0 */
    totalFileSize?: number;
    version?: string;
}
