/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface DockerStats {
    /** @minimum 0 */
    blockIoRead: number;
    /** @minimum 0 */
    blockIoWrite: number;
    cpuPercentage: number;
    id: string;
    /** @minimum 0 */
    memLimit: number;
    /** @minimum 0 */
    memUsage: number;
    name: string;
    /** @minimum 0 */
    networkRxBytes: number;
    /** @minimum 0 */
    networkTxBytes: number;
    /** @minimum 0 */
    pidCount: number;
    timestamp: string;
}
