/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface EditProfileFileRequest {
    /** File contents to write to the profile file */
    fileContent: string;
}
