/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { GameProperties } from './gameProperties';
import type { Mod } from './mod';
import type { Platform } from './platform';

export interface Game {
    admins: string[];
    crossPlatform: boolean;
    gameProperties: GameProperties;
    /** @minimum 0 */
    maxPlayers: number;
    mods: Mod[];
    modsRequiredByDefault: boolean;
    name: string;
    password: string;
    passwordAdmin: string;
    scenarioId: string;
    supportedPlatforms: Platform[];
    visible: boolean;
}
