/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface GameProperties {
    VONCanTransmitCrossFaction: boolean;
    VONDisableDirectSpeechUI: boolean;
    VONDisableUI: boolean;
    battlEye: boolean;
    disableThirdPerson: boolean;
    fastValidation: boolean;
    missionHeader: unknown;
    /** @minimum 0 */
    networkViewDistance: number;
    /** @minimum 0 */
    serverMaxViewDistance: number;
    /** @minimum 0 */
    serverMinGrassDistance: number;
}
