/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export type GetGlobalLogsParams = {
    /**
     * Page number (default: 1)
     * @minimum 0
     * @nullable
     */
    page?: number | null;
    /**
     * Items per page (default: 50)
     * @minimum 0
     * @nullable
     */
    limit?: number | null;
};
