/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export type GetWorkshopSort = (typeof GetWorkshopSort)[keyof typeof GetWorkshopSort];

export const GetWorkshopSort = {
    newest: 'newest',
    popularity: 'popularity',
    subscribers: 'subscribers',
    version_size: 'version_size'
} as const;
