/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { Branch } from './branch';
import type { ScenarioEntry } from './scenarioEntry';

export interface ListScenariosResponse {
    branch: Branch;
    scenarios: ScenarioEntry[];
}
