/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export type LogAction = (typeof LogAction)[keyof typeof LogAction];

export const LogAction = {
    ServerAdded: 'ServerAdded',
    ServerDeleted: 'ServerDeleted',
    ServerStarted: 'ServerStarted',
    ServerUpdated: 'ServerUpdated',
    ServerStopped: 'ServerStopped',
    ServerLogDeleted: 'ServerLogDeleted',
    ImagePullStarted: 'ImagePullStarted'
} as const;
