/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export type LogType = (typeof LogType)[keyof typeof LogType];

export const LogType = {
    consolelog: 'console.log',
    errorlog: 'error.log',
    scriptlog: 'script.log',
    crashlog: 'crash.log'
} as const;
