/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface Mod {
    modId: string;
    name: string;
    /** @nullable */
    required?: boolean | null;
    /** @nullable */
    version?: string | null;
}
