/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { JoinQueue } from './joinQueue';

export interface Operating {
    aiLimit: number;
    disableAI: boolean;
    disableCrashReporter: boolean;
    disableNavmeshStreaming?: string[];
    disableServerShutdown: boolean;
    joinQueue: JoinQueue;
    lobbyPlayerSynchronise: boolean;
    /** @minimum 0 */
    playerSaveTime: number;
    /** @minimum 0 */
    slotReservationTimeout: number;
}
