/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { PaginatedResponseLogDataItem } from './paginatedResponseLogDataItem';

export interface PaginatedResponseLog {
    /** Data */
    data: PaginatedResponseLogDataItem[];
    /**
     * Limit
     * @minimum 0
     */
    limit: number;
    /**
     * Page number
     * @minimum 0
     */
    page: number;
    /**
     * Total
     * @minimum 0
     */
    total: number;
    /**
     * Total pages
     * @minimum 0
     */
    total_pages: number;
}
