/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { LogAction } from './logAction';

export type PaginatedResponseGlobalLogDataItem = {
    action: LogAction;
    id?: string;
    /** @nullable */
    target?: string | null;
    timestamp: string;
};
