/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export type Platform = (typeof Platform)[keyof typeof Platform];

export const Platform = {
    PLATFORM_PC: 'PLATFORM_PC',
    PLATFORM_XBL: 'PLATFORM_XBL',
    PLATFORM_PSN: 'PLATFORM_PSN'
} as const;
