/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { Branch } from './branch';
import type { ServerConfig } from './serverConfig';
import type { StartupParameterWrapper } from './startupParameterWrapper';

export type PostServerBody = StartupParameterWrapper & {
    branch: Branch;
    config: ServerConfig;
    isRunning: boolean;
    name: string;
    /** @minimum 0 */
    playerCount: number;
    uuid?: string;
};
