/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface Preview {
    contentType: string;
    /** @minimum 0 */
    height: number;
    url: string;
    /** @minimum 0 */
    width: number;
}
