/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export interface PullLog {
    errorDetailCode: number;
    errorDetailMessage: string;
    id: string;
    progressDetailCurrent: number;
    progressDetailTotal: number;
    pullId?: string;
    status: string;
}
