/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface Ratings {
    /** @minimum 0 */
    dislikes: number;
    /** @minimum 0 */
    likes: number;
    rating: number;
}
