/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export interface Rcon {
    address: string;
    blacklist: string[];
    /** @minimum 0 */
    maxClients: number;
    password: string;
    permission: string;
    /** @minimum 0 */
    port: number;
    whitelist: string[];
}
