/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export interface ResultSize {
    /** @minimum 0 */
    addonsSize: number;
    logs: string[];
    /** @minimum 0 */
    logsSize: number;
    mods: string[];
    /** @minimum 0 */
    profileSize: number;
}
