/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { Log } from './log';

export interface ResultLogs {
    containsCrashReportLog: boolean;
    logs: Log[];
    success: boolean;
}
