/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface ResultSize {
    /** @minimum 0 */
    addonsSize: number;
    logs: string[];
    /** @minimum 0 */
    logsSize: number;
    mods: string[];
    /** @minimum 0 */
    profileSize: number;
}
