/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

/**
 * Image with pre-generated thumbnail URLs
 */
export interface ScenarioImage {
    contentType: string;
    /** @minimum 0 */
    height: number;
    url: string;
    /** @minimum 0 */
    width: number;
}
