/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { ScenarioImage } from './scenarioImage';

/**
 * A playable scenario bundled with an asset
 */
export interface Scenario {
    /**
     * Upstream omits this for some scenarios — not guaranteed present.
     * @nullable
     */
    authorName?: string | null;
    /**
     * Upstream omits this for some scenarios — not guaranteed present.
     * @nullable
     */
    description?: string | null;
    /** Enfusion game ID string, e.g. `{E2EC49F1…}Missions/…/Arland.conf` */
    gameId: string;
    /**
     * Upstream omits this for some scenarios — not guaranteed present.
     * @nullable
     */
    gameMode?: string | null;
    image?: null | ScenarioImage;
    name: string;
    /** @minimum 0 */
    playerCount: number;
}
