/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { A2s } from './a2s';
import type { Game } from './game';
import type { Operating } from './operating';
import type { Rcon } from './rcon';

export interface ServerConfig {
    a2s: A2s;
    bindAddress: string;
    /** @minimum 0 */
    bindPort: number;
    game: Game;
    operating: Operating;
    publicAddress: string;
    /** @minimum 0 */
    publicPort: number;
    rcon: Rcon;
}
