/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */
import type { StartupParameter } from './startupParameter';

export interface StartupParameterWrapper {
    startupParameters: StartupParameter[];
}
