/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * arsa-backend-rs
 * OpenAPI spec version: 0.1.0
 */

export interface StartupParameter {
    enabled: boolean;
    /** @nullable */
    maxVal?: number | null;
    /** @nullable */
    minVal?: number | null;
    parameter: string;
    tooltip: string;
    type: string;
    value?: unknown;
    /** @nullable */
    valueList?: string[] | null;
}
