/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */

export interface StartupParameter {
    enabled: boolean;
    /** @nullable */
    maxVal?: number | null;
    /** @nullable */
    minVal?: number | null;
    parameter: string;
    tooltip: string;
    type: string;
    value?: unknown;
    /** @nullable */
    valueList?: string[] | null;
}
