/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * arsa-backend
 * OpenAPI spec version: 2.0.0
 */
import type { AssetsPage } from './assetsPage';

/**
 * Top-level response returned by this proxy
 */
export interface WorkshopResponse {
    assets: AssetsPage;
}
